[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysql", "nodejs_20", "npm"]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  "composer install --no-dev --prefer-dist --optimize-autoloader",
  "npm ci",
  "npm run build"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan route:clear", 
  "php artisan view:clear",
  "php artisan event:clear",
  "php artisan config:cache",
  "php artisan view:cache"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public public/index.php"
